PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/hostyn/.local/bin"

# ================ XDG =============== #

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"

# ======= Autogenerated config ======= #

HISTFILE=~/.zsh_history 
HISTSIZE=1000
SAVEHIST=1000

setopt auto_cd
unsetopt beep extendedglob nomatch notify

# ======= Keybind configuration ======= #

# bindkey -e
bindkey "^[[H" beginning-of-line		# Home / Inicio
bindkey "^[[F" end-of-line					# End / Fin
bindkey "^[[1;5C" forward-word			# Ctr + Right
bindkey "^[[1;5D" backward-word			# Ctr + Left
bindkey "^[[3~" delete-char					# Supr
bindkey "^H" backward-delete-word		# Ctr + Return

# zstyle :compinstall filename '/home/hostyn/.zshrc'

# autoload -Uz compinit
# compinit

# ======= Nvm config ======= #
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
source /usr/share/nvm/init-nvm.sh

# ======= Plugins ======= #

source /home/hostyn/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /home/hostyn/.zsh/zsh-autosuggestions.zsh
source /home/hostyn/.zsh/zsh-sudo.zsh

# ======= Prompt ======= #

PROMPT="%B%F{200}%n%f %F{7}on%f %F{39}%~%f%b %(?..%B%F{red}%? %f%b) "

# ======= Dont save to history ======= #

setopt HIST_IGNORE_SPACE

# ======= Aliases ======= #

alias sudo='sudo '

alias ls='/bin/lsd -l --group-dirs=first'
alias la='/bin/lsd -la --group-dirs=first'

alias cat='/usr/bin/bat --pager ""'
alias catn='/usr/bin/bat'

alias vi='/usr/bin/nvim'
alias vim='/usr/bin/nvim'

alias py='python3'

alias upgrade='sudo paru'

alias ..='cd ..'

# ======= Functions ======= #

extract () {
     if [ -f $1 ] ; then
         case $1 in
             *.tar.bz2)   tar xjf $1     ;;
             *.tar.gz)    tar xzf $1     ;;
             *.bz2)       bunzip2 $1     ;;
             *.rar)       rar x $1       ;;
             *.gz)        gunzip $1      ;;
             *.tar)       tar xf $1      ;;
             *.tbz2)      tar xjf $1     ;;
             *.tgz)       tar xzf $1     ;;
             *.zip)       unzip $1       ;;
             *.Z)         uncompress $1  ;;
             *.7z)        7z x $1    ;;
             *)           echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

gitc () {
	if [ $# -eq 0 ] ; then 
		echo "Specify a commit name" 
		return 1
	fi
	git add .
	git status
	git commit -m $1
	git push
}
